debug: False
use_wandb: True
upload_to_hf_hub: True
sample_data: False
seed: -1

output_dir: ./artifacts
data_dir: ./data


wandb_project_name: WSDM-Cup-Multilingual-Chatbot-Arena
experiment_name: qwen2.5_7B_difflr
notes: 7B model with differential learning rate for head and body
train_file_name: train_split.parquet

model:
  model_name: Qwen/Qwen2.5-7B
  attn_implementation: flash_attention_2
  dtype: bfloat16
  qlora: false

tokenizer:
  max_length: 1024
  truncation: True
  padding_side: left
  truncation_side: left
  pad_to_multiple_of: 16

lora:
  r: 64
  alpha: 16
  target_modules: all-linear
  dropout: 0
  bias: none
  modules_to_save: ['score']

optimizer:
  name: AdamW8bit
  head_lr: 5.0e-5
  lr: 1.0e-4


trainer_args:
  eval_strategy: epoch
  save_strategy: "no"
  logging_strategy: steps
  logging_first_step: True
  logging_steps: 1
  eval_on_start: false
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 2
  learning_rate: ${optimizer.lr}
  num_train_epochs: 1
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.02
  bf16: true
  tf32: true
  bf16_full_eval: true
  group_by_length: true
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  torch_compile: true
  use_liger_kernel: false
  report_to: "wandb"
  weight_decay: 0.01
  max_grad_norm: 1000.0

  