debug: False
use_wandb: True
upload_to_hf_hub: True
sample_data: False
seed: -1

output_dir: ./artifacts
data_dir: ./data


wandb_project_name: WSDM-Cup-Multilingual-Chatbot-Arena
experiment_name: qwen2.5_3B_qlora_baseline
notes: qwen qlora baseline


train_file_name: train_split.parquet

model:
  model_name: Qwen/Qwen2.5-3B
  attn_implementation: flash_attention_2
  dtype: bfloat16

tokenizer:
  max_length: 1024
  truncation: True
  padding_side: left
  truncation_side: left
  pad_to_multiple_of: 16

lora:
  r: 64
  alpha: 16
  target_modules: all-linear

  dropout: 0
  bias: none
  modules_to_save: ['score']


trainer_args:
  eval_strategy: epoch
  save_strategy: "no"
  logging_strategy: steps
  logging_first_step: True
  logging_steps: 1
  eval_on_start: false
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-4
  num_train_epochs: 1
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.05
  bf16: true
  tf32: true
  bf16_full_eval: true
  optim: "paged_adamw_8bit"
  group_by_length: true
  gradient_checkpointing: true
  torch_compile: false
  use_liger_kernel: false
  report_to: "wandb"
  weight_decay: 0.01
  max_grad_norm: 1000.0

  